ocubom_twig_extra:

    # Twig Html Extension
    html:

        # Enable or disable this extension
        enabled: true

        # Compress HTML output
        compression:
            # Force compression
            force: false
            # The level of compression to use
            level: smallest # One of "none"; "fastest"; "normal"; "smallest"

    # Twig Svg Extension
    svg:

        # Enable or disable this extension
        enabled: true

        # SVG providers.
        providers:

            # Local File System provider.
            file_system:
                # Enable or disable Local File System provider.
                enabled: true
                # The paths where Local File System provider will search files.
                paths:
                    - '%kernel.project_dir%/assets'
                    - '%kernel.project_dir%/node_modules'

            # FontAwesome provider.
            font_awesome:
                # Enable or disable FontAwesome provider.
                enabled: true
                # The paths where FontAwesome provider will search files.
                paths:
                    - '%kernel.project_dir%/node_modules/@fortawesome/fontawesome-pro/svgs'
                    - '%kernel.project_dir%/node_modules/@fortawesome/fontawesome-free/svgs'
                    - '%kernel.project_dir%/vendor/fortawesome/font-awesome/svgs/'

            # Iconify provider.
            iconify:
                # Enable or disable Iconify provider.
                enabled: true
                # The paths where Iconify provider will search files.
                paths:
                    - '%kernel.project_dir%/node_modules/@iconify-json/'
                    - '%kernel.project_dir%/node_modules/@iconify/json/'
                    - '%kernel.project_dir%/vendor/iconify/json/'
                # Iconify custom loader options
                loader:
                    # Enable cache on this path (empty to disable).
                    cache_dir: '%kernel.cache_dir%/iconify'
                # Iconify custom runtime configuration
                runtime:
                    # Enable SVG Framework Server Side Rendering on classes (empty to disable).
                    svg_framework:
                        - iconify
                        - iconify-inline
                    # Enable Web Component Server Side Rendering on tags (empty to disable).
                    web_component:
                        - icon
                        - iconify-icon

    # Twig Webpack_encore Extension
    webpack_encore:

        # Enable or disable this extension
        enabled: true

        # Paths where Symfony Encore will generate its output.
        output_paths:
            - '%kernel.project_dir%/public/build'

    # HTTP headers that must be set.
    # The listener will only be registered if at least one rule is enabled.
    #http_headers:
    #
    #    # Duplicate robots meta as X-Robots-Tag
    #    # @see https://developers.google.com/search/docs/advanced/robots/robots_meta_tag#xrobotstag
    #    -   name:    'X-Robots-Tag'
    #        pattern: '@[\p{Zs}]*<meta\s+(?:name="robots"\s+content="([^"]+)"|content="([^"]+)"\s+name="robots")\s*/?\s*>\p{Zs}*\n?@i'
    #        value:   '%2$s'
    #        replace: '%1$s'
    #        formats:
    #            - 'text/html'
    #
    #    # Disable Metro Interface
    #    # @see https://github.com/h5bp/html5-boilerplate/blob/5.3.0/dist/doc/extend.md#prompt-users-to-switch-to-desktop-mode-in-ie10-metro
    #    -   name:    'X-UA-Compatible'
    #        enabled: true
    #        pattern: '@[\p{Zs}]*<meta\s+(?:http-equiv="X-UA-Compatible"\s+content="([^"]+)"|content="([^"]+)"\s+http-equiv="X-UA-Compatible")\s*>\p{Zs}*\n?@i'
    #        value:   '%2$s'
    #        replace: '' # Delete the meta tag as is not standard
    #        formats:
    #            - 'text/html'
